global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        username: 'rupakg'
      - channel: '#monitoring'
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
