global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'node resources'
    static_configs:
      - targets:
        - 'node-exp:9100'
    # dns_sd_configs:
    #   - names: ['tasks.node-exp']
    #     type: 'A'
    #     port: 9100
    params:
      collect[]:
        - cpu
        - meminfo
        - diskstats
        - netdev
        - netstat

  - job_name: 'node storage'
    # Override the global default and scrape targets from this job every 1 minute.
    scrape_interval: 1m
    static_configs:
      - targets:
        - 'node-exp:9100'
    # dns_sd_configs:
    #   - names: ['tasks.node-exp']
    #     # type: 'A'
    #     port: 9100
    params:
      collect[]:
        - filefd
        - filesystem
        - xfs

  - job_name: 'cadvisor'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'cadvisor:8080'
    # dns_sd_configs:
    #   - names: ['tasks.cadvisor']
    #     type: 'A'
    #     port: 8081